### ISSUE TITLE
Doesn't work anymore with IP address

### ISSUE THREAD

**Issue by myrandor** [utdream/mod_cfml#9]
I'm using it with Lucee. I develop locally on 127.0.0.1 and after compiling the latest .so module for my computer, all my link calling 127.0.0.1 doesn't work. I have to use 'localhost' explicitly.

Note that it worked from the version I got here:
https://github.com/utdream/mod_cfml/tree/master/C

Using Apache/2.4.10 64 bits on a Mac OSX Yosemite 10.10.3 and Apache Tomcat 8.0.23.

**Comment by nopjmp** [comment]
Could you turn on the following in your apache config and restart both Apache and Tomcat and provide us with the verbose output? 
```
LogHeaders true
LogHandlers true
LogAliases true
```

**Comment by utdream** [comment]
Hi @myrandor, can you confirm that this is still an issue?
